version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: devityDB
      DB_USERNAME: user
      DB_PASSWORD: test1234
    command: php artisan serve --host=0.0.0.0 --port=8080


  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devityDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
